spring:
  datasource:
    # Substitua 'nome_do_seu_banco' pelo nome que você criará no pgAdmin
    url: jdbc:postgresql://localhost:5432/portfolio_db
    username: postgres
    password: "@Wall1327"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      # 'update' cria as tabelas automaticamente e as atualiza se você mudar suas classes @Entity
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        # Melhora a visualização do SQL no console
        format_sql: true
        
springdoc:
  swagger-ui:
    # Caminho personalizado para acessar a interface
    path: /swagger-ui.html
  api-docs:
    # Caminho para o JSON da documentação
    path: /v3/api-docs